# Generated by Django 2.2 on 2019-05-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=100, verbose_name='Nombre del proyecto')),
                ('descripcion', models.TextField(verbose_name='Descripción del Proyecto')),
                ('imagen', models.ImageField(upload_to='proyectos/', verbose_name='Imagen del Producto Final')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Nombre del título')),
            ],
            options={
                'verbose_name': 'Titulo',
                'verbose_name_plural': 'Titulos',
            },
        ),
    ]
